os: linux
dist: xenial
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
arch:
  - amd64
  - ppc64le
install:
  - pip install tox-travis
script:
  - tox

matrix:
  include:
    - python: "3.9"
      env: TOXENV=flake8
